### ISSUE TITLE
Test airdrop tooling & add logic with new update

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#109]
https://github.com/Reecepbcups/airdrop-tools

Get a Juno / AKT / Cosmos export @ any block height & test the tooling works with it as well as the osmo one

write tool to iterate through all lines & parse data correctly

Relook at #17 @ merge logic over into it

Then merge into scripts/airdrop

**Comment by vuong177** [comment]
@Reecepbcups do you think oke if we create seperate repo for airdrop ?

**Comment by Reecepbcups** [comment]
> @Reecepbcups should we create seperate repo for airdrop ?

@vuong177 I think that would be smart yes. If you can create it and add me to it with full permissions that would be great :)

**Comment by vuong177** [comment]
https://github.com/notional-labs/craft-airdrop

I added you as admin !

**Comment by Reecepbcups** [comment]
Thank you! Will push to this tomorrow :)
