### ISSUE TITLE
[DRAFT] Consensus Failure

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#123]
## Problem
Consensus Failure since upgrade w/ test_node.sh
- https://gist.github.com/Reecepbcups/93a06f1d28b92e8fccad94a52ce5ec22
- [Craftd Version Ubuntu laptop go1.17.6](https://gist.github.com/Reecepbcups/93a06f1d28b92e8fccad94a52ce5ec22?permalink_comment_id=4199350#gistcomment-4199350)
- [Craftd version arch server go1.18](https://gist.github.com/Reecepbcups/93a06f1d28b92e8fccad94a52ce5ec22?permalink_comment_id=4199355#gistcomment-4199355)

## Tested OSs
Ubuntu 18.04 bionic | x86_64 Linux 5.0.0-36-generic | Dell XPS Laptop
Arch Linux | x86_64 Linux 5.16.15-arch1-1 | Hetzner Server

## Steps
I was running on last commit before today (`git reset --hard 6509b94ae60b9925703220422ba1636e1e2591e5`) & had an open RPC & rest server up on the machine.

I upgraded to latest (`git pull` `git checkout v0.4.0`) then `go install ./...`. When I ran ./test_node.sh again, I got the following
https://gist.github.com/Reecepbcups/93a06f1d28b92e8fccad94a52ce5ec22 (line 65)

I have since deleted ~/go/bin ~/go/pkg to try and revert back to the previous working version, but to no luck.

**Comment by vuong177** [comment]
I'm working at this!

**Comment by vuong177** [comment]
yo, @Reecepbcups @faddat, I fixed this bug and pushed in master branch! It from missing staking hook in app.go !
