### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by faddat** [notional-labs/craft#17]
Please use this issue to document the intended airdrop design as carefully as possible.  

It is likely to be the largest blocker to genesis.

**Comment by Reecepbcups** [comment]
Bump on Airdrop @Thomas-Rivera &/or @ChandraStation

**Comment by ChandraStation** [comment]
# Craft Economy Airdrop Design

The Craft Economy Airdrop can be split into 6 separate groups:

## Group 1 - All Stakers

All peoples delegated to any node (Except for Centralized Exchanges) on the following networks will receive the $CRAFT AIrdrop

- Akash
- Osmosis
- Cosmos Hub
- Juno

## Group 2 - LP's

Any people providing liquidity in the following pools on Osmosis will receive a portion of the $CRAFT Airdrop 

- Pool # 1
- Pool # 561

## Group 3 - Delegators to Atom relayers

A collective list of validators that run Atom relayers

- Cephalopod
- Cros Nest
- Notional
- Vitwit
- Strangelove

The peoples delegated to the above Validators (Must find the rest) will receive a portion of the $CRAFT airdrop 

## Group 4 - Chandra Delegators

Any peoples delegated to any Chandra Station validator on any network will receive a portion of the $CRAFT airdrop

## Group 5 - ION Holders

Any peoples who hold $ION will receive a portion of the $CRAFT airdrop. This includes ION that is being LP'd

## Group 6 - Craft Economy Genesis Validators

Any peoples delegated to the Craft Economy genesis set on their networks of choice will receive a portion of the $CRAFT airdrop. The validators and their respective networks are as follows 

- @kingnodes: Chihuahua Chain
- @crosnest_com: http://Crypto.org | Atom | Osmosis
- @NosNodes: Juno | Osmosis
- @imperator_co: Atom | Osmosis | Juno SpacePotato - Akash | Juno | Osmosis
- @SkyNetValidator: Osmosis | Akash | Juno
- @ThePizzaTech: Desmos | G-Bridge
- @AltcoinPsycho: Akash | Sentinel | Persistence
- @notionaldao: Osmosis | Huahua | Juno
- @Sentinel_co: Osmosis | Atom | Comdex
- @forbole: Akash | Cosmos Hub | http://Crypto.org | Osmosis
- @nodes_smart: Osmosis | Juno | Atom
- @vitwit_: Atom | Akash | Osmosis | Juno | Regen
- @OmniFlixNetwork: Juno | Stargaze | Osmosis

(Pending further additions next week)

**Comment by ChandraStation** [comment]
Command for viewing who's delegated to Chandra Station on Akash and printing to readable file (can be extrapolated for groups 6 4 & 3
```bash
akash q staking delegations-to akashvaloper1lxh0u07haj646pt9e0l2l4qc3d8htfx5kk698d --node http://localhost:16657 > akt.txt
```
Guide for snapshotting LP's 

https://docs.osmosis.zone/integrate/airdrops.html#overview

All stakers of a network can be done by exporting the state height I think?

**Comment by Reecepbcups** [comment]
Update: https://blog.crafteconomy.io/airdrop.html

Am beginning to work on a script for this

**Comment by Reecepbcups** [comment]
Moved development to https://github.com/notional-labs/craft-airdrop

Only exports are needed for any chain we want. I hardcode the valop addresses for genesis validators + their bonus drop at time of calulation

We can merge back in closer to release once it has been finished & tested :)

**Comment by Reecepbcups** [comment]
All airdrop is being redone by Cabcon due to the collapse of Terra & other economic factors. Will be handling via discord once we get beta up. Ill handle all the scripts in the above repo once we are ready
