### ISSUE TITLE
Upstream: fix "craftd keys list"

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#36]
migrate err: config.info: key not foundmigrate err: data.info: key not foundmigrate err: keyhash.info: key not foundEnter keyring passphrase:
Error: read /root/.craftd/config: is a directory

**Comment by faddat** [comment]
I suspect that this is an operating system issue.  what os on your server?

**Comment by Reecepbcups** [comment]
Ubuntu 20.04 focal
x86_64 Linux 5.4.0-90-generic 

after reboot: 
`Error: No such interface “org.freedesktop.DBus.Properties” on object at path /`

x86_64 Linux 5.16.15-arch1-1

and also Vuongs monjaro arch issue

**Comment by nguyenvuong1122000** [comment]
@Reecepbcups, there are some wrong thing in cosmos-sdk.
I fixed it and seem it work in main.

**Comment by Reecepbcups** [comment]
> @Reecepbcups, there are something wrong in our cosmos-sdk. I fixed it and key list cli working again.

confirmed working on my end now, thank you!

**Comment by faddat** [comment]
@nguyenvuong1122000 great work!  Did you make a PR to the cosmos SDK?

**Comment by faddat** [comment]
@nguyenvuong1122000 hey so I thought that I could open a PR, then add you to it, but it seems that a PR corresponds to only individual humans. 

Here's what I did when I submitted it:

* merged master branch of sdk into yours so it will merge cleanly for sure
* made the PR

Super great work, and thank you so much!  I'll close my PR tomorrow when you open yours.

**Comment by nguyenvuong1122000** [comment]
@faddat, sr for my late reply. I think i need check it more deeply before create a PR. It can be a breaking change.
