### ISSUE TITLE
cannot create key with Ledger

### ISSUE THREAD

**Issue by Galadrin** [notional-labs/craft#40]
Following the command provided is the HowTo, I cannot create a key with a Ledger :
```
go install ./...
[...]
~/go/bin/craftd keys add craft_testnet --ledger
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: support for ledger devices is not available in this executable
```

**Comment by Reecepbcups** [comment]
> Following the command provided is the HowTo, I cannot create a key with a Ledger :
> 
> ```
> go install ./...
> [...]
> ~/go/bin/craftd keys add craft_testnet --ledger
> Error: failed to generate ledger key: failed to retrieve device: ledger nano S: support for ledger devices is not available in this executable
> ```


Please attempt installing with the following:
go install -tags ledger ./...

Then see if you can correctly add the key
