### ISSUE TITLE
Prepare NFT implementations list

### ISSUE THREAD

**Issue by faddat** [notional-labs/craft#5]
* CosmWasm
	* Implement the protobufs in cosmos-sdk like stargaze

* Cosmos-sdk
	*  NFT module in comsos-sdk (not sure if complete)

* Irismod
	* Not sure if this is relevant, since iris did https://github.com/bianjieai/tibc-go

* onft
  * nft standard from omniflix team

Give @Reecepbcups a menu of ways to do NFTs so we can choose one.  Run this past @shanev from Stargaze.

**Comment by Reecepbcups** [comment]
Assume this can be closed with the implementation of NFTc from Vuong
I've been messing with oNFT testnet. So long as I can set attributes for NFTs I am good
