### ISSUE TITLE
Request for generating Tx

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#8]
**Issue**
Currently the only way for me to generate a transaction in game is with 
`craftd tx bank send <FROM> <TO> <AMOUNT>token --chain-id craft --generate-only`

While this can work, it is a crutch being the only request not done with the Blockchain API/Tendermint. 
(Currently has to run the binary with java runtime, then parse JSON correctly to save to Redis
Overall keeping everything in 1 place will make things more efficient / easier to implement equally.

**Proposal**
Implement Query on :1317 or :26657 to return a generated JSON transaction.

**Example**
http://localhost:26657/gen_tx?from=craft1234...&to=craft5678...&amount=5&memo="Some Desc Here"

**Returns**
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"craft1234","to_address":"craft5678","amount":[{"denom":"token","amount":"5"}]}],"memo":"Some Desc Here","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

Then memo can be used in the webapp & in game to describe transactions
 
 Change #1 - will just hardcode transaction within Integration plugin rather than need to use an endpoint
 
 No longer needed, done in game:
~~When generating a Tx, is it possible to also have a TxUUID?
If so, returning a unique transaction hash with it would allow for me to save that as `Map<TxID, Map<PlayerID, MetaData>>` in game while waiting for it to be signed. Then I can iterate redis keys, check signed TxID’s, and run the MetaData for the UUID
I assume not but worth knowing just incase it is~~

**Comment by faddat** [comment]
hey, sorry that I just saw this.

Maybe. 

I can sayu for certain we can do something like this. 

I've templated transactions in the past.  

About the uuid, let's call :)

**Comment by Reecepbcups** [comment]
Visual Idea (TxFlow, Left Side)
https://www.canva.com/design/DAE0DWNnCQc/N5WkcNnmgAAF5JxmJuckAg/view?website#2

**Comment by Reecepbcups** [comment]
> hey, sorry that I just saw this.
> 
> Maybe.
> 
> I can sayu for certain we can do something like this.
> 
> I've templated transactions in the past.
> 
> About the uuid, let's call :)

Visual Idea (TxFlow, Left Side)
https://www.canva.com/design/DAE0DWNnCQc/N5WkcNnmgAAF5JxmJuckAg/view?website#2

**Comment by Reecepbcups** [comment]
Simplified complexity thanks to Jacob, reduced to

```java
public static String generateJSONAminoTx(String FROM, String TO, long AMOUNT, String DESCRIPTION) {
        return "{\"body\":{\"messages\":[{\"@type\":\"/cosmos.bank.v1beta1.MsgSend\",\"from_address\":\""+FROM+"\",\"to_address\":\""+TO+"\",\"amount\":[{\"denom\":\"token\",\"amount\":\""+AMOUNT+"\"}]}],\"memo\":\""+DESCRIPTION+"\",\"timeout_height\":\"0\",\"extension_options\":[],\"non_critical_extension_options\":[]},\"auth_info\":{\"signer_infos\":[],\"fee\":{\"amount\":[],\"gas_limit\":\"200000\",\"payer\":\"\",\"granter\":\"\"}},\"signatures\":[]}";
    }
```

Will then be saved to REDIS for webapp to grab, sign, and broadcast
