### ISSUE TITLE
entire validator set gets jailed for downtime except chandra station

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#88]
Majority unbonded at block height 1001 (looks like 75% of the set)

https://gist.github.com/Reecepbcups/f57bd5fc9257b2d9a239601c4f7dca7d

4:11EST - March 24th US time:
active val: 12
jailed val: 30

by 5:18am, only Chandra Station was active

**Comment by faddat** [comment]
think it is the heavy stake allocation to Chandra.  we need to restart to determine.

**Comment by Reecepbcups** [comment]
resolved with v0.2.2 & equal stake weighting
