### ISSUE TITLE
"Replay: BlockPart" & "Replay: Vote blockID" Spam when starting a validator

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/craft#98]
https://gist.github.com/Reecepbcups/cc77dd8ba6815811fc22c77024771076

**Comment by nguyenvuong1122000** [comment]
i think it from bad peer. I don't have this problem when start node.

**Comment by Reecepbcups** [comment]
Is a peering issue, will reopen if beta of SDK does not fix
